#! /bin/bash

set -e

VOLUME_NAME=${1:?"Use $0 <chik> to start the development environment"}
FREE_PORT=${2:-8000}
CODE_PORT=${3:-8080}


# build the container
echo "Building the development container"
docker build -t ${VOLUME_NAME} -f Dockerfile_${VOLUME_NAME} .


if [[ $(docker volume ls --filter "name=${VOLUME_NAME}" -q | wc -l ) -eq 0 ]]; then
    echo "creating volume and copying setup script into it"
    docker volume create --name ${VOLUME_NAME}
    docker run -it --rm -v ${VOLUME_NAME}:/workdir busybox \
     /bin/sh -c "mkdir -p /workdir/src && chown -R 1000:1000 /workdir"
fi

echo "Cleaning up old containers"
docker rmi $(docker images -qa -f 'dangling=true') || echo "Nothing to remove"

echo "Starting the development container"
docker run --rm -it --privileged -v ${VOLUME_NAME}:/home/yoctouser -p ${FREE_PORT}:8000 -p ${CODE_PORT}:8080 ${VOLUME_NAME}
