#! /bin/bash

set -e
VOLUME_NAME=chik-devel

# build the container
echo "Building the development container"
docker build -t ${VOLUME_NAME} .


if [[ $(docker volume ls --filter "name=${VOLUME_NAME}" -q | wc -l ) -eq 0 ]]; then
    echo "creating volume and copying setup script into it"
    docker volume create --name ${VOLUME_NAME}
    docker run -it --rm -v ${VOLUME_NAME}:/workdir -v ${PWD}/resources:/resources busybox \
     /bin/sh -c "mkdir -p /workdir/src && cp -r /resources/* /workdir/src/ && chown -R 1000:1000 /workdir"
fi

echo "Starting the development container"
docker run --rm -it -v ${VOLUME_NAME}:/home/yoctouser chik-devel