#!/bin/bash

set -e
set -u

HERE="~/src"

board=unipi-neuron
yocto_version=zeus
directory=${HOME}/src

function main {
    mkdir -p ${directory}
    cd ${directory}
    fetch_yocto
    start_subshell
}

function check_n_get {
    if [[ -d $1 ]]; then
        return
    fi

    echo "Cloning $1"
    git clone $2 -b $3 $1
}

function fetch_yocto {
    mkdir -p yocto/src
    pushd yocto/src
        check_n_get poky https://git.yoctoproject.org/git/poky ${yocto_version}
        check_n_get meta-openembedded https://github.com/openembedded/meta-openembedded.git ${yocto_version}
        check_n_get meta-raspberrypi https://github.com/agherzan/meta-raspberrypi.git ${yocto_version}
        check_n_get meta-swupdate https://github.com/sbabic/meta-swupdate.git ${yocto_version}
        check_n_get meta-chik git@github.com:GoChik/meta-chik.git master
    popd
}

function start_subshell {
    cd yocto
    set +u
    export MACHINE=${board}
    export PATH="${HERE}:${PATH}"
    export PROMPT_COMMAND="PS1='(yocto) \[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '"
    export TEMPLATECONF="/opt/tools/defconfig"

    source src/poky/oe-init-build-env "build-${board}"
    exec bash -i
}

main ${@}