#! /bin/bash

set -e

VOLUME_NAME=${1?"Missing volume name parameter"}

# create volume and set volume permissions
if [[ $(docker volume ls --filter "name=chik" -q | wc -l ) -eq 0 ]]; then
    echo "creating volume"
    docker volume create --name ${VOLUME_NAME}
    docker run -it --rm -v ${VOLUME_NAME}:/workdir busybox chown -R 1000:1000 /workdir
fi

# start the filesharing container
if [[ $(docker ps -a --filter "name=${VOLUME_NAME}-share" | wc -l) -eq 1 ]]; then
    echo "Creating machine"
    docker create -t -p 445:445 --name ${VOLUME_NAME}-share -v ${VOLUME_NAME}:/workdir crops/samba
fi
docker start ${VOLUME_NAME}-share
sudo ifconfig lo0 127.0.0.2 alias up

# start the yocto container
docker run --rm -it -v ${VOLUME_NAME}:/workdir crops/poky --workdir=/workdir